"""initial_schema

Revision ID: 81af6cfbd43d
Revises: 
Create Date: 2026-04-14 13:47:11.313118+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81af6cfbd43d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('structure_count', sa.Integer(), nullable=False),
    sa.Column('extraction_time_ms', sa.Float(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inchi_key', sa.String(length=27), nullable=False),
    sa.Column('inchi', sa.Text(), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('extended_smiles', sa.Text(), nullable=False),
    sa.Column('molecular_formula', sa.String(length=255), nullable=False),
    sa.Column('svg', sa.Text(), nullable=False),
    sa.Column('mdlv3000', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inchi_key')
    )
    op.create_table('extraction_substances',
    sa.Column('extraction_id', sa.BigInteger(), nullable=False),
    sa.Column('substance_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substance_id'], ['substances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extraction_id', 'substance_id'),
    sa.UniqueConstraint('extraction_id', 'substance_id', name='uq_extraction_substance')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_substances')
    op.drop_table('substances')
    op.drop_table('extractions')
    # ### end Alembic commands ###
