#!/usr/bin/env python3
"""Generate the claymorphic README badge chips (light + dark variants).

Static chips (status, license, tech row) are committed to assets/readme/badges/.
The two live chips (tests, lint) are regenerated by CI with the real workflow
status and pushed to the `badges` branch — see .github/workflows/{test,lint}.yml.

Usage:
    python3 scripts/generate_badges.py                          # all static chips
    python3 scripts/generate_badges.py --ci tests --status failing --out /tmp/b

Stdlib only, deterministic output: same inputs always produce byte-identical
SVGs, so re-running never creates noisy diffs.
"""

from __future__ import annotations

import argparse
import pathlib

# Palette families, matched to the hero/stack artwork (#1E2A78 / #096779 /
# #c61354 — note these differ from the retired shields.io colors on purpose).
PALETTES = {
    "light": {
        "navy": dict(top="#eceffd", bot="#c7d0f4", dot="#2e3da3", val="#1E2A78"),
        "teal": dict(top="#e0f4f5", bot="#b0dde0", dot="#096779", val="#075e66"),
        "crimson": dict(top="#fde6ef", bot="#f4bdd3", dot="#c61354", val="#b3104b"),
    },
    "dark": {
        "navy": dict(top="#323e90", bot="#222b63", dot="#97a3f2", val="#bcc5f8"),
        "teal": dict(top="#11626f", bot="#0a4550", dot="#74d2da", val="#abe3e7"),
        "crimson": dict(top="#92194a", bot="#6b1037", dot="#f190b8", val="#f5abc8"),
    },
}
THEME = {
    "light": dict(ink="#0a1547", sheen="0.9", shadow_opacity="0.4", dot_hl="0.8"),
    "dark": dict(ink="#eef1fd", sheen="0.22", shadow_opacity="0.7", dot_hl="0.4"),
}
# Drop shadows are tinted by the chip family in light mode, near-black in dark.
SHADOW = {
    "light": {"navy": "#1E2A78", "teal": "#096779", "crimson": "#c61354"},
    "dark": {"navy": "#02040d", "teal": "#02040d", "crimson": "#02040d"},
}

# Approximate advance widths for Inter 700 at 13px. Close enough that the pill
# padding absorbs the error; tweak here if a new label visibly over/underflows.
_NARROW = {"i": 3.7, "l": 3.7, "j": 4.0, "f": 4.6, "t": 4.9, "r": 5.2, ".": 3.5,
           " ": 3.6, "-": 4.9, "/": 4.4, ":": 3.5, "+": 7.8, "I": 4.2}
_WIDE = {"m": 11.6, "w": 10.4, "M": 11.3, "W": 12.2}


def _text_width(s: str) -> float:
    w = 0.0
    for ch in s:
        if ch in _NARROW:
            w += _NARROW[ch]
        elif ch in _WIDE:
            w += _WIDE[ch]
        elif ch.isupper():
            w += 9.0
        else:
            w += 7.4
    return w


def chip_svg(label: str, value: str, family: str, theme: str, aria: str) -> str:
    pal, th = PALETTES[theme][family], THEME[theme]
    x_label = 27.0
    x_value = x_label + _text_width(label) + 5.0
    width = round(x_value + _text_width(value) + 13.0)
    font = "Inter, ui-sans-serif, system-ui, sans-serif"
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="36" viewBox="0 0 {width} 36" role="img" aria-label="{aria}">
  <title>{aria}</title>
  <defs>
    <linearGradient id="b" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="{pal["top"]}"/>
      <stop offset="100%" stop-color="{pal["bot"]}"/>
    </linearGradient>
    <linearGradient id="s" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#ffffff" stop-opacity="{th["sheen"]}"/>
      <stop offset="100%" stop-color="#ffffff" stop-opacity="0"/>
    </linearGradient>
    <filter id="d" x="-20%" y="-40%" width="140%" height="200%">
      <feDropShadow dx="0" dy="3" stdDeviation="2.6" flood-color="{SHADOW[theme][family]}" flood-opacity="{th["shadow_opacity"]}"/>
    </filter>
  </defs>
  <rect x="5" y="2" width="{width - 10}" height="26" rx="13" fill="url(#b)" filter="url(#d)"/>
  <rect x="6.5" y="3.5" width="{width - 13}" height="12" rx="6" fill="url(#s)"/>
  <circle cx="18" cy="15" r="4" fill="{pal["dot"]}"/>
  <circle cx="16.8" cy="13.8" r="1.3" fill="#ffffff" opacity="{th["dot_hl"]}"/>
  <g font-family="{font}" font-size="13" font-weight="700">
    <text x="{x_label}" y="19.5" fill="{th["ink"]}">{label}</text>
    <text x="{x_value:g}" y="19.5" fill="{pal["val"]}">{value}</text>
  </g>
</svg>
"""


# id, label, value, family, aria
STATIC_CHIPS = [
    ("status", "status", "pre-release", "crimson", "Project status: pre-release"),
    ("license", "license", "MIT", "navy", "License: MIT"),
    ("python", "Python", "3.11+", "navy", "Python 3.11+"),
    ("fastapi", "FastAPI", "0.135", "teal", "FastAPI 0.135"),
    ("react", "React", "19", "navy", "React 19"),
    ("cdk", "CDK", "2.12", "teal", "CDK 2.12"),
    ("postgres", "PostgreSQL", "16", "navy", "PostgreSQL 16"),
    ("docker", "Docker", "Compose", "teal", "Docker Compose"),
]


def write_chip(out: pathlib.Path, chip_id: str, label: str, value: str,
               family: str, aria: str) -> None:
    for theme in ("light", "dark"):
        path = out / f"{chip_id}-{theme}.svg"
        path.write_text(chip_svg(label, value, family, theme, aria), encoding="utf-8")
        print(f"wrote {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ci", choices=["tests", "lint"],
                        help="generate a single live CI chip instead of the static set")
    parser.add_argument("--status", choices=["passing", "failing"], default="passing",
                        help="CI chip status (only with --ci)")
    parser.add_argument("--out", type=pathlib.Path,
                        default=pathlib.Path(__file__).resolve().parent.parent
                        / "assets" / "readme" / "badges")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    if args.ci:
        family = "teal" if args.status == "passing" else "crimson"
        write_chip(args.out, args.ci, args.ci, args.status, family,
                   f"{args.ci}: {args.status}")
    else:
        for chip_id, label, value, family, aria in STATIC_CHIPS:
            write_chip(args.out, chip_id, label, value, family, aria)


if __name__ == "__main__":
    main()
